name: Free Games Bot Workflow

on:
  schedule:
    # هر روز در ساعت 05:00 UTC اجرا می‌شود (مثلاً 08:30 صبح به وقت تهران در تابستان)
    - cron: '0 5 * * *'
  workflow_dispatch:
    # اجازه می‌دهد تا به صورت دستی از رابط کاربری GitHub Actions اجرا شود
  push:
    branches:
      - main
    paths:
      - 'src/**' # در صورت تغییر در کدهای منبع ربات اجرا شود
      - '.github/workflows/run_bot.yml' # در صورت تغییر در این فایل اجرا شود

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    permissions:
      contents: write # برای اجازه push کردن تغییرات به مخزن نیاز است

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # از نسخه پایتون مورد نظر خود استفاده کنید

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # نصب کتابخانه‌های موجود در requirements.txt
          
      - name: Install Playwright browsers
        run: playwright install --with-deps chromium # نصب مرورگر Chromium و وابستگی‌های آن

      - name: Ensure data directories exist
        run: |
          mkdir -p data # اطمینان از وجود دایرکتوری data
          mkdir -p web_data # اطمینان از وجود دایرکتوری web_data
          mkdir -p cache # اطمینان از وجود دایرکتوری cache (جدید)

      - name: Run Free Games Bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          # DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }} # اگر از DeepL استفاده می‌کنید، این خط را فعال کنید
        run: python -m src.main # <--- این خط اصلاح شده است

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          # اضافه کردن فایل‌ها به منطقه staging گیت
          # --force برای اطمینان از اضافه شدن حتی اگر محتوا تغییر نکرده باشد
          git add --force data/games.db web_data/free_games.json
          
          # بررسی اینکه آیا چیزی برای کامیت وجود دارد یا خیر (حتی اگر --force استفاده شده باشد)
          # این شرط برای جلوگیری از ایجاد کامیت‌های خالی است
          if git diff --staged --quiet; then
            echo "No changes to commit (after staging). Skipping commit."
          else
            git commit -m "chore: Update games database and web data"
            # Push changes to the repository
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # توکن پیش‌فرض GitHub Actions
