name: Rayegan Game Bot Runner

on:
  # اجرای زمان‌بندی شده با استفاده از سینتکس cron
  schedule:
    - cron: '0 8,20 * * *'
  
  # این گزینه به شما اجازه می‌دهد تا گردش کار را به صورت دستی از طریق رابط کاربری گیت‌هاب اجرا کنید
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run the bot script and commit changes
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }} # اختیاری
        run: |
          # اطمینان از وجود دایرکتوری web_data
          mkdir -p web_data 
          
          # اجرای اسکریپت اصلی ربات
          python src/main.py

          # تنظیمات Git برای کامیت
          git config user.name "Rayegan Game Bot"
          git config user.email "actions@github.com"
          
          # اضافه کردن فایل‌ها به منطقه staging گیت
          # --force برای اطمینان از اضافه شدن حتی اگر محتوا تغییر نکرده باشد
          git add --force data/games.db web_data/free_games.json 
          
          # بررسی اینکه آیا چیزی برای کامیت وجود دارد یا خیر (حتی اگر --force استفاده شده باشد)
          # این شرط برای جلوگیری از ایجاد کامیت‌های خالی است
          if git diff --staged --quiet; then
            echo "No changes to commit (after staging). Skipping commit."
          else
            git commit -m "chore: Update games database and web data"
            # Push changes to the repository
            git push
          fi
