name: Rayegan Game Bot Runner

on:
  # اجرای زمان‌بندی شده با استفاده از سینتکس cron
  schedule:
    - cron: '0 8,20 * * *'
  
  # این گزینه به شما اجازه می‌دهد تا گردش کار را به صورت دستی از طریق رابط کاربری گیت‌هاب اجرا کنید
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name: Run the bot script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: |
          python src/main.py
          # اطمینان از وجود دایرکتوری web_data قبل از کامیت (اگر اسکریپت پایتون آن را ایجاد نکند)
          mkdir -p web_data

      - name: Commit database and web data changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Update games database and web data"
          file_pattern: |
            data/games.db
            web_data/free_games.json # اضافه شده: برای کامیت فایل JSON
          commit_user_name: Rayegan Game Bot
          commit_user_email: actions@github.com
          commit_author: Rayegan Game Bot <actions@github.com>
